[platformio]
default_envs = esp32dev_app
extra_configs = platformio_override.ini

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = ..\shared_libs

[env:esp32dev_scan]
extends = env
build_flags =
  -D SENSOR_ID_SCAN_ONLY=1
lib_deps =
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.4

[env:esp32dev_app]
extends = env
build_flags =
  -D SENSOR_ID_SCAN_ONLY=0
  -D BBH_BOOTSTRAP_BROKER_HOST=\"10.24.16.94\"
  -D BBH_BOOTSTRAP_BROKER_PORT=1883
  -D BBH_BOOTSTRAP_CLAIM_TOPIC=\"bbh/iot/bootstrap/claim\"
  -D BBH_BOOTSTRAP_REPLY_PREFIX=\"bbh/iot/bootstrap/reply\"
lib_deps =
  bblanchon/ArduinoJson @ ^7
  256dpi/MQTT @ ^2.5.2
  tzapu/WiFiManager @ ^2.0.17
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.4
