[platformio]
default_envs = esp32dev_app

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32dev_scan]
extends = env
build_flags =
  -D SENSOR_ID_SCAN_ONLY=1
lib_deps =
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.4

[env:esp32dev_app]
extends = env
build_flags =
  -D SENSOR_ID_SCAN_ONLY=0
lib_deps =
  bblanchon/ArduinoJson @ ^7
  tzapu/WiFiManager @ ^2.0.17
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.4
